int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int i);
void jack_bauer(void);
int add(int a, int b);
void print_to_98(int n);
void reset_to_98(int *n);
void swap_int(int *a, int *b);
int _strlen(char *s);
void _puts(char *str);
void print_rev(char *s);
void rev_string(char *s);
void puts2(char *str);
void puts_half(char *str);
char *_strcat(char *dest, char *src);
void reverse_array(int *a, int n);
char *string_toupper(char *);
char *cap_string(char *);
int _strcmp(char *s1, char *s2);
char *_memset(char *s, char b, unsigned int n);
